CREATE TABLE IF NOT EXISTS `vehicle_documents` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `plate` VARCHAR(16) NOT NULL,
    `owner_identifier` VARCHAR(80) DEFAULT NULL,
    `owner_name` VARCHAR(128) DEFAULT NULL,
    `model_name` VARCHAR(80) DEFAULT NULL,
    `model_label` VARCHAR(128) DEFAULT NULL,
    `vin` VARCHAR(40) DEFAULT NULL,
    `engine_code` VARCHAR(40) DEFAULT NULL,
    `fuel_text` VARCHAR(80) DEFAULT NULL,
    `tier` INT NOT NULL DEFAULT 1,
    `inspection_done_at` DATETIME DEFAULT NULL,
    `inspection_valid_until` DATETIME DEFAULT NULL,
    `issued_at` DATETIME DEFAULT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'inspected',
    `invalid_reason` VARCHAR(255) DEFAULT NULL,
    `serial` VARCHAR(40) DEFAULT NULL,
    `display_data` LONGTEXT DEFAULT NULL,
    `properties` LONGTEXT DEFAULT NULL,
    `mod_hash` VARCHAR(80) DEFAULT NULL,
    `last_seen_hash` VARCHAR(80) DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_vehicle_documents_plate` (`plate`),
    KEY `idx_vehicle_documents_owner` (`owner_identifier`),
    KEY `idx_vehicle_documents_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
